-- 베이스라인 스키마 (MariaDB). prod 프로파일이 쓴다.
--
-- H2 판(db/migration/h2/V1__baseline.sql)과 내용은 같고 타입 표기만 다르다.
--   timestamp(6)                      -> datetime(6)
--   generated by default as identity  -> not null auto_increment
--   boolean                           -> bit
--   테이블 끝에 engine=InnoDB
--
-- 그래서 두 파일을 한 개로 합치지 않았다. 하나로 합치려면 공통 문법만 써야 하는데,
-- 그러면 Hibernate 가 생성한 타입과 달라져 ddl-auto: validate 가 어느 한쪽에서 깨진다.
--
-- 이 DDL 도 손으로 쓴 게 아니라 Hibernate MariaDBDialect 가 생성한 것이다.
--   ./gradlew bootRun --args="--spring.profiles.active=test \
--     --spring.jpa.hibernate.ddl-auto=none \
--     --spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect \
--     --spring.jpa.properties.jakarta.persistence.schema-generation.scripts.action=create \
--     --spring.jpa.properties.jakarta.persistence.schema-generation.scripts.create-target=build/ddl-mariadb.sql"
--
-- 주의: 이 스크립트는 MariaDB 에 실제로 실행해 검증하지 못했다(작업 환경에 Docker 없음).
-- `docker compose up --build` 로 한 번 확인할 것. 실패하면 Flyway 가 기동을 중단시키고
-- 어느 SQL 에서 깨졌는지 로그에 남긴다 — ddl-auto: update 처럼 조용히 넘어가지 않는다.

create table member (
    created_at    datetime(6) not null,
    id            bigint not null auto_increment,
    nickname      varchar(20) not null,
    login_id      varchar(30) not null,
    provider_id   varchar(50),
    password      varchar(255) not null,
    auth_provider varchar(10) default 'LOCAL' not null,
    role          enum ('ADMIN','USER') not null,
    primary key (id)
) engine=InnoDB;

create table performance (
    base_price        integer,
    end_date          date,
    latitude          float(53),
    longitude         float(53),
    start_date        date,
    total_seat_count  integer,
    id                bigint not null auto_increment,
    running_time      varchar(30),
    venue_facility_id varchar(30),
    venue_hall_id     varchar(30),
    age_limit         varchar(50),
    region            varchar(50),
    external_id       varchar(100) not null,
    genre             varchar(100),
    title             varchar(200) not null,
    venue             varchar(200),
    address           varchar(300),
    cast_members      varchar(500),
    poster_url        varchar(500),
    description       varchar(1000),
    category          enum ('CIRCUS_MAGIC','CLASSIC','COMPLEX','CONCERT','DANCE','ETC','MUSICAL','PLAY','TRADITIONAL'),
    source_type       enum ('CULTURE','KOPIS','SEED','STANDARD'),
    primary key (id)
) engine=InnoDB;

create table performance_schedule (
    remaining_seats integer not null,
    total_seats     integer not null,
    id              bigint not null auto_increment,
    performance_id  bigint not null,
    show_at         datetime(6) not null,
    version         bigint,
    primary key (id)
) engine=InnoDB;

create table reservation (
    amount          integer not null,
    canceled_at     datetime(6),
    confirmed_at    datetime(6),
    created_at      datetime(6) not null,
    hold_expires_at datetime(6) not null,
    id              bigint not null auto_increment,
    member_id       bigint not null,
    schedule_id     bigint not null,
    reservation_no  varchar(20) not null,
    seat_summary    varchar(500),
    payment_key     varchar(255),
    status          enum ('CANCELED','CONFIRMED','EXPIRED','PENDING') not null,
    primary key (id)
) engine=InnoDB;

create table seat (
    aisle_after    bit not null,
    price          integer not null,
    row_no         integer not null,
    seat_no        integer not null,
    id             bigint not null auto_increment,
    reservation_id bigint,
    schedule_id    bigint not null,
    version        bigint,
    section        varchar(20) not null,
    grade          enum ('A','R','S','VIP') not null,
    status         enum ('AVAILABLE','HELD','SOLD') not null,
    primary key (id)
) engine=InnoDB;

create table seat_hold (
    expires_at datetime(6) not null,
    member_id  bigint not null,
    seat_id    bigint not null,
    primary key (seat_id)
) engine=InnoDB;

create table sync_state (
    last_synced_on date not null,
    source_type    enum ('CULTURE','KOPIS','SEED','STANDARD') not null,
    primary key (source_type)
) engine=InnoDB;

alter table member add constraint uk_member_login_id unique (login_id);
alter table performance add constraint uk_performance_external unique (external_id);
alter table performance_schedule add constraint uk_schedule unique (performance_id, show_at);
alter table reservation add constraint uk_reservation_no unique (reservation_no);
alter table seat add constraint uk_seat unique (schedule_id, section, row_no, seat_no);

create index idx_performance_period on performance (start_date, end_date);
create index idx_schedule_showat on performance_schedule (show_at);
create index idx_reservation_member on reservation (member_id);
create index idx_seat_schedule_status on seat (schedule_id, status);

alter table performance_schedule
    add constraint fk_schedule_performance foreign key (performance_id) references performance (id);

alter table reservation
    add constraint fk_reservation_schedule foreign key (schedule_id) references performance_schedule (id);

alter table seat
    add constraint fk_seat_reservation foreign key (reservation_id) references reservation (id);

alter table seat
    add constraint fk_seat_schedule foreign key (schedule_id) references performance_schedule (id);
