-- 베이스라인 스키마 (H2, MODE=MySQL). local·test 프로파일이 쓴다.
--
-- 이 DDL 은 손으로 쓴 게 아니라 Hibernate 가 자기 dialect 로 생성한 것을 옮긴 것이다.
-- ddl-auto: validate 가 이 스키마를 검사하므로, 엔티티가 기대하는 형태와 한 글자라도
-- 어긋나면 기동할 때 걸린다. 새로 만들 때는 아래 방식으로 다시 뽑는 게 안전하다.
--
--   ./gradlew bootRun --args="--spring.profiles.active=test \
--     --spring.jpa.hibernate.ddl-auto=none \
--     --spring.jpa.properties.jakarta.persistence.schema-generation.scripts.action=create \
--     --spring.jpa.properties.jakarta.persistence.schema-generation.scripts.create-target=build/ddl-h2.sql"
--
-- 생성물에서 두 가지만 손봤다.
--   1) 외래키 이름을 해시(FK1si4d884ndg3bq9hwsi3uado0)에서 읽을 수 있는 이름으로 교체.
--      Hibernate 버전에 따라 해시가 바뀌어 마이그레이션이 재현되지 않는다.
--      validate 는 외래키 이름을 보지 않으므로 안전하다.
--   2) `alter table if exists` 의 `if exists` 제거. 마이그레이션에서는 테이블이 반드시 있다.

create table member (
    created_at    timestamp(6) not null,
    id            bigint generated by default as identity,
    nickname      varchar(20) not null,
    login_id      varchar(30) not null,
    provider_id   varchar(50),
    password      varchar(255) not null,
    auth_provider varchar(10) default 'LOCAL' not null,
    role          enum ('ADMIN','USER') not null,
    primary key (id),
    constraint uk_member_login_id unique (login_id)
);

create table performance (
    base_price        integer,
    end_date          date,
    latitude          float(53),
    longitude         float(53),
    start_date        date,
    total_seat_count  integer,
    id                bigint generated by default as identity,
    running_time      varchar(30),
    venue_facility_id varchar(30),
    venue_hall_id     varchar(30),
    age_limit         varchar(50),
    region            varchar(50),
    external_id       varchar(100) not null,
    genre             varchar(100),
    title             varchar(200) not null,
    venue             varchar(200),
    address           varchar(300),
    cast_members      varchar(500),
    poster_url        varchar(500),
    description       varchar(1000),
    category          enum ('CIRCUS_MAGIC','CLASSIC','COMPLEX','CONCERT','DANCE','ETC','MUSICAL','PLAY','TRADITIONAL'),
    source_type       enum ('CULTURE','KOPIS','SEED','STANDARD'),
    primary key (id),
    constraint uk_performance_external unique (external_id)
);

create table performance_schedule (
    remaining_seats integer not null,
    total_seats     integer not null,
    id              bigint generated by default as identity,
    performance_id  bigint not null,
    show_at         timestamp(6) not null,
    version         bigint,
    primary key (id),
    constraint uk_schedule unique (performance_id, show_at)
);

create table reservation (
    amount          integer not null,
    canceled_at     timestamp(6),
    confirmed_at    timestamp(6),
    created_at      timestamp(6) not null,
    hold_expires_at timestamp(6) not null,
    id              bigint generated by default as identity,
    member_id       bigint not null,
    schedule_id     bigint not null,
    reservation_no  varchar(20) not null,
    seat_summary    varchar(500),
    payment_key     varchar(255),
    status          enum ('CANCELED','CONFIRMED','EXPIRED','PENDING') not null,
    primary key (id),
    constraint uk_reservation_no unique (reservation_no)
);

create table seat (
    aisle_after    boolean not null,
    price          integer not null,
    row_no         integer not null,
    seat_no        integer not null,
    id             bigint generated by default as identity,
    reservation_id bigint,
    schedule_id    bigint not null,
    version        bigint,
    section        varchar(20) not null,
    grade          enum ('A','R','S','VIP') not null,
    status         enum ('AVAILABLE','HELD','SOLD') not null,
    primary key (id),
    constraint uk_seat unique (schedule_id, section, row_no, seat_no)
);

create table seat_hold (
    expires_at timestamp(6) not null,
    member_id  bigint not null,
    seat_id    bigint not null,
    primary key (seat_id)
);

create table sync_state (
    last_synced_on date not null,
    source_type    enum ('CULTURE','KOPIS','SEED','STANDARD') not null,
    primary key (source_type)
);

create index idx_performance_period on performance (start_date, end_date);
create index idx_schedule_showat on performance_schedule (show_at);
create index idx_reservation_member on reservation (member_id);
create index idx_seat_schedule_status on seat (schedule_id, status);

alter table performance_schedule
    add constraint fk_schedule_performance foreign key (performance_id) references performance;

alter table reservation
    add constraint fk_reservation_schedule foreign key (schedule_id) references performance_schedule;

alter table seat
    add constraint fk_seat_reservation foreign key (reservation_id) references reservation;

alter table seat
    add constraint fk_seat_schedule foreign key (schedule_id) references performance_schedule;
