-- 알림. 지금은 "찜한 공연에 예매 가능한 회차가 열렸다" 하나뿐이라 type 이 한 값이지만,
-- 종류가 늘어날 걸 보고 컬럼으로 뺐다(마감 임박, 취소표 등).
--
-- member_id 는 FK 를 걸지 않는다. wishlist·reservation 과 같은 방식으로 표를 맞췄다.
-- performance_id 는 FK 를 건다 — 수집 규칙에 안 맞는 공연은 실제로 지워지므로
-- (PerformanceSyncService.purgeNonPerformances) 참조가 남으면 안 된다.
create table notification (
    id             bigint generated by default as identity,
    member_id      bigint not null,
    performance_id bigint not null,
    type           varchar(30) not null,
    created_at     timestamp(6) not null,
    -- null 이면 안 읽음. 읽은 시각을 남기는 게 boolean 보다 나중에 쓸 데가 많다.
    read_at        timestamp(6),
    primary key (id),
    -- 중복 발송 방지의 최종 방어. 동기화는 매일 도는데 이력이 없으면 같은 공연으로 매일
    -- 알림이 쌓인다 — 알림 기능이 스팸이 되는 가장 흔한 실패다. 발송 쪽에서 미리 걸러도
    -- 실행이 겹치면 뚫리므로 DB 가 막는다 (NotificationService 가 이 위반을 "이미 보냄"으로 해석한다).
    constraint uk_notification unique (member_id, performance_id, type)
);

-- 마이페이지 알림 목록은 "내 것을 최근 순으로"만 조회한다.
create index idx_notification_member on notification (member_id, created_at);

alter table notification
    add constraint fk_notification_performance foreign key (performance_id) references performance;
