-- 저장한 검색. 목록 화면에서 "이 조건 저장"을 누르면 그때의 필터(장르·지역·월·검색어)를
-- 남긴다. 매일 새벽 공연 수집 배치가 새 공연을 등록할 때마다 저장된 조건과 맞춰 보고,
-- 맞으면 알림을 만든다(NotificationType.SAVED_SEARCH_MATCH) — 재방문 이유를 만드는
-- 기능이라 사람이 다시 검색하지 않아도 알아서 알려주는 게 핵심이다.
--
-- 요일·시간대·공연장은 저장 대상에서 뺐다. 이 넷(장르·지역·월·검색어)은 성격이
-- "무엇을 보고 싶은가"인데, 요일·시간대는 "언제 갈 수 있는가"에 가깝다 — 새 공연이
-- 등록되는 시점엔 아직 회차 시각이 사용자 사정(그날 저녁에 갈 수 있는지)과 무관하고,
-- 공연장은 지역보다 좁은 축이라 지역만으로도 충분히 좁혀진다.
create table saved_search (
    id            bigint generated by default as identity,
    member_id     bigint not null,
    label         varchar(100) not null,
    category      varchar(30),
    region        varchar(50),
    -- "month" 는 H2/MariaDB 예약어(MONTH() 함수)라 그대로 쓰면 구문 오류가 난다.
    -- FacetCountRow 가 "key" 를 "label" 로 바꾼 것과 같은 종류의 회피다.
    search_month  integer,
    keyword       varchar(100),
    created_at    timestamp(6) not null,
    primary key (id)
);

-- 마이페이지 "저장한 검색" 목록(내 것만, 최근 순)과 배치의 매칭 조회 둘 다가 쓴다.
create index idx_saved_search_member on saved_search (member_id);
